// Standardized list of college (NCAA-sponsored, plus a few common emerging)
// sports, split by gender to match how programs and rosters are actually
// organized (e.g. "Men's Swimming & Diving" and "Women's Swimming & Diving"
// are separate sports/teams). Rifle and Skiing are run as coed, single-division
// "National Collegiate" sports and are listed once, unprefixed.
export const COLLEGE_SPORTS: string[] = [
  "Women's Acrobatics & Tumbling",
  "Men's Baseball",
  "Men's Basketball",
  "Women's Basketball",
  "Women's Beach Volleyball",
  "Women's Bowling",
  "Men's Cross Country",
  "Women's Cross Country",
  "Women's Equestrian",
  "Men's Fencing",
  "Women's Fencing",
  "Women's Field Hockey",
  "Women's Flag Football",
  "Men's Football",
  "Men's Golf",
  "Women's Golf",
  "Men's Gymnastics",
  "Women's Gymnastics",
  "Men's Ice Hockey",
  "Women's Ice Hockey",
  "Men's Lacrosse",
  "Women's Lacrosse",
  "Rifle",
  "Women's Rowing",
  "Women's Rugby",
  "Skiing",
  "Men's Soccer",
  "Women's Soccer",
  "Women's Softball",
  "Women's Stunt",
  "Men's Swimming & Diving",
  "Women's Swimming & Diving",
  "Men's Tennis",
  "Women's Tennis",
  "Men's Track & Field",
  "Women's Track & Field",
  "Women's Triathlon",
  "Men's Volleyball",
  "Women's Volleyball",
  "Men's Water Polo",
  "Women's Water Polo",
  "Men's Wrestling",
  "Women's Wrestling",
];
