// Standardized list of NCAA Division I member institutions.
// Source: Wikipedia "List of NCAA Division I institutions" (2025-26 season).
// `name` is the actual/official full university name — the standardized value
// stored in the database (e.g. "University of California, Berkeley", not "Cal").
// `aliases` are short/common names, legal-charter names, and mascots used only
// for search matching — never stored.
export interface NCAASchool {
  name: string;
  aliases: string[];
}

/** All searchable strings for a school: its canonical name plus every alias. */
function searchableTerms(school: NCAASchool): string[] {
  return [school.name, ...school.aliases];
}

/**
 * Returns the school whose canonical name or an alias matches `query` exactly
 * (case-insensitive). Used to auto-resolve typed text that happens to already
 * be a standardized name, e.g. typing "ohio state" should resolve to
 * "The Ohio State University".
 */
export function findExactSchoolMatch(query: string): NCAASchool | undefined {
  const q = query.trim().toLowerCase();
  if (!q) return undefined;
  return NCAA_SCHOOLS.find((school) => searchableTerms(school).some((t) => t.toLowerCase() === q));
}

/**
 * Ranked, fuzzy-ish search over school names, legal names, and nicknames.
 * Exact matches rank first, then prefix matches, then substring matches.
 */
export function searchSchools(query: string, limit = 8): NCAASchool[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const scored: { school: NCAASchool; score: number }[] = [];
  for (const school of NCAA_SCHOOLS) {
    let best = Infinity;
    for (const term of searchableTerms(school)) {
      const t = term.toLowerCase();
      let score: number | undefined;
      if (t === q) score = 0;
      else if (t.startsWith(q)) score = 1;
      else if (t.includes(q)) score = 2;
      else if (q.split(/\s+/).every((part) => t.includes(part))) score = 3;
      if (score !== undefined && score < best) best = score;
    }
    if (best < Infinity) scored.push({ school, score: best });
  }

  scored.sort((a, b) => a.score - b.score || a.school.name.localeCompare(b.school.name));
  return scored.slice(0, limit).map((s) => s.school);
}

export const NCAA_SCHOOLS: NCAASchool[] = [
  { name: 'Abilene Christian University', aliases: ['Abilene Christian', 'Wildcats'] },
  { name: 'Alabama Agricultural and Mechanical University', aliases: ['Alabama A&M', 'Bulldogs'] },
  { name: 'Alabama State University', aliases: ['Alabama State', 'Hornets'] },
  { name: 'Alcorn State University', aliases: ['Alcorn State', 'Braves'] },
  { name: 'American University', aliases: ['American', 'Eagles'] },
  { name: 'Appalachian State University', aliases: ['Appalachian State', 'Mountaineers'] },
  { name: 'Arizona State University', aliases: ['Arizona State', 'Sun Devils'] },
  { name: 'Arkansas State University', aliases: ['Arkansas State', 'Red Wolves'] },
  { name: 'Auburn University', aliases: ['Auburn', 'Tigers'] },
  { name: 'Austin Peay State University', aliases: ['Austin Peay', 'Governors'] },
  { name: 'Ball State University', aliases: ['Ball State', 'Cardinals'] },
  { name: 'Baylor University', aliases: ['Baylor', 'Bears'] },
  { name: 'Bellarmine University', aliases: ['Bellarmine', 'Knights'] },
  { name: 'Belmont University', aliases: ['Belmont', 'Bruins'] },
  { name: 'Bethune–Cookman University', aliases: ['Bethune–Cookman', 'Wildcats'] },
  { name: 'Boise State University', aliases: ['Boise State', 'Broncos'] },
  { name: 'Boston College', aliases: ['Eagles'] },
  { name: 'Boston University', aliases: ['Terriers'] },
  { name: 'Bowling Green State University', aliases: ['Bowling Green', 'Falcons'] },
  { name: 'Bradley University', aliases: ['Bradley', 'Braves'] },
  { name: 'Brigham Young University', aliases: ['BYU', 'Cougars'] },
  { name: 'Brown University', aliases: ['Bears', 'Brown'] },
  { name: 'Bryant University', aliases: ['Bryant', 'Bulldogs'] },
  { name: 'Bucknell University', aliases: ['Bison', 'Bucknell'] },
  { name: 'Butler University', aliases: ['Bulldogs', 'Butler'] },
  { name: 'California Baptist University', aliases: ['Cal Baptist', 'Lancers'] },
  { name: 'California Polytechnic State University', aliases: ['Cal Poly', 'Mustangs'] },
  { name: 'California State University, Bakersfield', aliases: ['Bakersfield', 'Roadrunners'] },
  { name: 'California State University, Fresno', aliases: ['Bulldogs', 'Fresno State'] },
  { name: 'California State University, Fullerton', aliases: ['Cal State Fullerton', 'Titans'] },
  { name: 'California State University, Long Beach', aliases: ['Beach', 'Long Beach State'] },
  { name: 'California State University, Northridge', aliases: ['CSUN', 'Cal State Northridge', 'Matadors'] },
  { name: 'California State University, Sacramento', aliases: ['Hornets', 'Sacramento State'] },
  { name: 'Campbell University', aliases: ['Campbell', 'Fighting Camels'] },
  { name: 'Canisius University', aliases: ['Canisius', 'Golden Griffins'] },
  { name: 'Central Connecticut State University', aliases: ['Blue Devils', 'Central Connecticut'] },
  { name: 'Central Michigan University', aliases: ['Central Michigan', 'Chippewas'] },
  { name: 'Charleston Southern University', aliases: ['Buccaneers', 'Charleston Southern'] },
  { name: 'Chicago State University', aliases: ['Chicago State', 'Cougars'] },
  { name: 'Clemson University', aliases: ['Clemson', 'Tigers'] },
  { name: 'Cleveland State University', aliases: ['Cleveland State', 'Vikings'] },
  { name: 'Coastal Carolina University', aliases: ['Chanticleers', 'Coastal Carolina'] },
  { name: 'Colgate University', aliases: ['Colgate', 'Raiders'] },
  { name: 'College of Charleston', aliases: ['Charleston', 'Cougars'] },
  { name: 'College of the Holy Cross', aliases: ['Crusaders', 'Holy Cross'] },
  { name: 'Colorado State University', aliases: ['Colorado State', 'Rams'] },
  { name: 'Columbia University', aliases: ['Columbia', 'Columbia University in the City of New York', 'Lions'] },
  { name: 'Coppin State University', aliases: ['Coppin State', 'Eagles'] },
  { name: 'Cornell University', aliases: ['Big Red', 'Cornell'] },
  { name: 'Creighton University', aliases: ['Bluejays', 'Creighton'] },
  { name: 'Dartmouth College', aliases: ['Big Green', 'Dartmouth'] },
  { name: 'Davidson College', aliases: ['Davidson', 'Wildcats'] },
  { name: 'Delaware State University', aliases: ['Delaware State', 'Hornets'] },
  { name: 'DePaul University', aliases: ['Blue Demons', 'DePaul'] },
  { name: 'Drake University', aliases: ['Bulldogs', 'Drake'] },
  { name: 'Drexel University', aliases: ['Dragons', 'Drexel'] },
  { name: 'Duke University', aliases: ['Blue Devils', 'Duke'] },
  { name: 'Duquesne University', aliases: ['Dukes', 'Duquesne', 'Duquesne University of the Holy Spirit'] },
  { name: 'East Carolina University', aliases: ['East Carolina', 'Pirates'] },
  { name: 'Eastern Illinois University', aliases: ['Eastern Illinois', 'Panthers'] },
  { name: 'Eastern Kentucky University', aliases: ['Colonels', 'Eastern Kentucky'] },
  { name: 'Eastern Michigan University', aliases: ['Eagles', 'Eastern Michigan'] },
  { name: 'Eastern Washington University', aliases: ['Eagles', 'Eastern Washington'] },
  { name: 'East Tennessee State University', aliases: ['Buccaneers', 'East Tennessee State'] },
  { name: 'East Texas A&M University', aliases: ['East Texas A&M', 'Lions'] },
  { name: 'Elon University', aliases: ['Elon', 'Phoenix'] },
  { name: 'Fairfield University', aliases: ['Fairfield', 'Stags'] },
  { name: 'Fairleigh Dickinson University', aliases: ['Fairleigh Dickinson', 'Knights'] },
  { name: 'Florida Agricultural and Mechanical University', aliases: ['Florida A&M', 'Rattlers'] },
  { name: 'Florida Atlantic University', aliases: ['Florida Atlantic', 'Owls'] },
  { name: 'Florida Gulf Coast University', aliases: ['Eagles', 'FGCU'] },
  { name: 'Florida International University', aliases: ['FIU', 'Panthers'] },
  { name: 'Florida State University', aliases: ['FSU', 'Florida State', 'Seminoles'] },
  { name: 'Fordham University', aliases: ['Fordham', 'Rams'] },
  { name: 'Furman University', aliases: ['Furman', 'Paladins'] },
  { name: 'Gardner–Webb University', aliases: ['Gardner–Webb', "Runnin' Bulldogs"] },
  { name: 'George Mason University', aliases: ['George Mason', 'Patriots'] },
  { name: 'Georgetown University', aliases: ['Georgetown', 'Hoyas'] },
  { name: 'Georgia Institute of Technology', aliases: ['Georgia Tech', 'Yellow Jackets'] },
  { name: 'Georgia Southern University', aliases: ['Eagles', 'Georgia Southern'] },
  { name: 'Georgia State University', aliases: ['Georgia State', 'Panthers'] },
  { name: 'Gonzaga University', aliases: ['Bulldogs', 'Gonzaga'] },
  { name: 'Grambling State University', aliases: ['Grambling State', 'Tigers'] },
  { name: 'Grand Canyon University', aliases: ['Antelopes', 'Grand Canyon'] },
  { name: 'Hampton University', aliases: ['Hampton', 'Pirates'] },
  { name: 'Harvard University', aliases: ['Crimson', 'Harvard'] },
  { name: 'High Point University', aliases: ['High Point', 'Panthers'] },
  { name: 'Hofstra University', aliases: ['Hofstra', 'Pride'] },
  { name: 'Houston Christian University', aliases: ['Houston Christian', 'Huskies'] },
  { name: 'Howard University', aliases: ['Bison', 'Howard'] },
  { name: 'Idaho State University', aliases: ['Bengals', 'Idaho State'] },
  { name: 'Illinois State University', aliases: ['Illinois State', 'Redbirds'] },
  { name: 'Indiana State University', aliases: ['Indiana State', 'Sycamores'] },
  { name: 'Indiana University Bloomington', aliases: ['Hoosiers', 'Indiana'] },
  { name: 'Indiana University Indianapolis', aliases: ['IU Indy', 'Jaguars'] },
  { name: 'Iona University', aliases: ['Gaels', 'Iona'] },
  { name: 'Iowa State University', aliases: ['Cyclones', 'Iowa State', 'Iowa State University of Science and Technology'] },
  { name: 'Jackson State University', aliases: ['Jackson State', 'Tigers'] },
  { name: 'Jacksonville State University', aliases: ['Gamecocks', 'Jax State'] },
  { name: 'Jacksonville University', aliases: ['Dolphins', 'Jacksonville'] },
  { name: 'James Madison University', aliases: ['Dukes', 'James Madison'] },
  { name: 'Kansas State University', aliases: ['Kansas State', 'Wildcats'] },
  { name: 'Kennesaw State University', aliases: ['Kennesaw State', 'Owls'] },
  { name: 'Kent State University', aliases: ['Golden Flashes', 'Kent State'] },
  { name: 'Lafayette College', aliases: ['Lafayette', 'Leopards'] },
  { name: 'Lamar University', aliases: ['Cardinals', 'Lamar'] },
  { name: 'La Salle University', aliases: ['Explorers', 'La Salle'] },
  { name: 'Lehigh University', aliases: ['Lehigh', 'Mountain Hawks'] },
  { name: 'Stanford University', aliases: ['Cardinal', 'Leland Stanford Junior University', 'Stanford'] },
  { name: 'Liberty University', aliases: ['Flames', 'Liberty'] },
  { name: 'Lindenwood University', aliases: ['Lindenwood', 'Lions and Lady Lions'] },
  { name: 'Lipscomb University', aliases: ['Bisons', 'Lipscomb'] },
  { name: 'Long Island University', aliases: ['LIU', 'Sharks'] },
  { name: 'Longwood University', aliases: ['Lancers', 'Longwood'] },
  { name: 'Louisiana State University', aliases: ['LSU', 'LSU Tigers', 'Louisiana State University and Agricultural and Mechanical College', 'Tigers'] },
  { name: 'Louisiana Tech University', aliases: ['Bulldogs', 'Louisiana Tech'] },
  { name: 'Loyola Marymount University', aliases: ['Lions', 'Loyola Marymount'] },
  { name: 'Loyola University Chicago', aliases: ['Loyola Chicago', 'Ramblers'] },
  { name: 'Loyola University Maryland', aliases: ['Greyhounds', 'Loyola'] },
  { name: 'Manhattan University', aliases: ['Jaspers', 'Manhattan'] },
  { name: 'Marist University', aliases: ['Marist', 'Red Foxes'] },
  { name: 'Marquette University', aliases: ['Golden Eagles', 'Marquette'] },
  { name: 'Marshall University', aliases: ['Marshall', 'Thundering Herd'] },
  { name: 'McNeese State University', aliases: ['Cowboys', 'McNeese'] },
  { name: 'Mercer University', aliases: ['Bears', 'Mercer'] },
  { name: 'Merrimack College', aliases: ['Merrimack', 'Warriors'] },
  { name: 'Miami University', aliases: ['Miami (Ohio)', 'Miami OH', 'RedHawks'] },
  { name: 'Michigan State University', aliases: ['MSU', 'Michigan State', 'Spartans'] },
  { name: 'Middle Tennessee State University', aliases: ['Blue Raiders', 'Middle Tennessee'] },
  { name: 'Mississippi State University', aliases: ['Bulldogs', 'Mississippi State'] },
  { name: 'Mississippi Valley State University', aliases: ['Delta Devils', 'Mississippi Valley State'] },
  { name: 'Missouri State University', aliases: ['Bears', 'Missouri State'] },
  { name: 'Monmouth University', aliases: ['Hawks', 'Monmouth'] },
  { name: 'Montana State University', aliases: ['Bobcats', 'Montana State'] },
  { name: 'Morehead State University', aliases: ['Eagles', 'Morehead State'] },
  { name: 'Morgan State University', aliases: ['Bears', 'Morgan State'] },
  { name: "Mount St. Mary's University", aliases: ["Mount Saint Mary's University", "Mount St. Mary's", 'Mountaineers'] },
  { name: 'Murray State University', aliases: ['Murray State', 'Racers'] },
  { name: 'New Jersey Institute of Technology', aliases: ['Highlanders', 'NJIT'] },
  { name: 'New Mexico State University', aliases: ['Aggies', 'New Mexico State'] },
  { name: 'Niagara University', aliases: ['Niagara', 'Purple Eagles'] },
  { name: 'Nicholls State University', aliases: ['Colonels', 'Nicholls'] },
  { name: 'Norfolk State University', aliases: ['Norfolk State', 'Spartans'] },
  { name: 'North Carolina Agricultural and Technical State University', aliases: ['Aggies', 'North Carolina A&T'] },
  { name: 'North Carolina Central University', aliases: ['Eagles', 'North Carolina Central'] },
  { name: 'North Carolina State University', aliases: ['NC State', 'Wolfpack'] },
  { name: 'North Dakota State University', aliases: ['Bison', 'North Dakota State', 'North Dakota State University of Agriculture and Applied Sciences'] },
  { name: 'Northeastern University', aliases: ['Huskies', 'Northeastern'] },
  { name: 'Northern Arizona University', aliases: ['Lumberjacks', 'Northern Arizona'] },
  { name: 'Northern Illinois University', aliases: ['Huskies', 'Northern Illinois'] },
  { name: 'Northern Kentucky University', aliases: ['Norse', 'Northern Kentucky'] },
  { name: 'Northwestern State University of Louisiana', aliases: ['Demons', 'Northwestern State'] },
  { name: 'Northwestern University', aliases: ['Northwestern', 'Wildcats'] },
  { name: 'Oakland University', aliases: ['Golden Grizzlies', 'Oakland'] },
  { name: 'Oklahoma State University', aliases: ['Cowboys', 'Oklahoma State', 'Oklahoma State University–Stillwater'] },
  { name: 'Old Dominion University', aliases: ['Monarchs', 'Old Dominion'] },
  { name: 'Oral Roberts University', aliases: ['Golden Eagles', 'Oral Roberts'] },
  { name: 'Oregon State University', aliases: ['Beavers', 'Oregon State'] },
  { name: 'Pepperdine University', aliases: ['Pepperdine', 'Waves'] },
  { name: 'Portland State University', aliases: ['Portland State', 'Vikings'] },
  { name: 'Prairie View A&M University', aliases: ['Panthers', 'Prairie View A&M'] },
  { name: 'Presbyterian College', aliases: ['Blue Hose', 'Presbyterian'] },
  { name: 'Princeton University', aliases: ['Princeton', 'Tigers'] },
  { name: 'Providence College', aliases: ['Friars', 'Providence'] },
  { name: 'Purdue University', aliases: ['Boilermakers', 'Purdue'] },
  { name: 'Purdue University Fort Wayne', aliases: ['Mastodons', 'Purdue Fort Wayne'] },
  { name: 'Queens University of Charlotte', aliases: ['Queens (NC)', 'Royals'] },
  { name: 'Quinnipiac University', aliases: ['Bobcats', 'Quinnipiac'] },
  { name: 'Radford University', aliases: ['Highlanders', 'Radford'] },
  { name: 'Rider University', aliases: ['Broncs', 'Rider'] },
  { name: 'Robert Morris University', aliases: ['Colonials', 'Robert Morris'] },
  { name: 'Rutgers University', aliases: ['Rutgers', 'Rutgers University–New Brunswick', 'Scarlet Knights'] },
  { name: 'Sacred Heart University', aliases: ['Pioneers', 'Sacred Heart'] },
  { name: 'Saint Bonaventure University', aliases: ['Bonnies', 'Saint Bonaventure'] },
  { name: 'Saint Francis University', aliases: ['Red Flash', 'Saint Francis'] },
  { name: "Saint John's University", aliases: ['Red Storm', "Saint John's"] },
  { name: "Saint Joseph's University", aliases: ['Hawks', "Saint Joseph's"] },
  { name: 'Saint Louis University', aliases: ['Billikens', 'Saint Louis'] },
  { name: "Saint Mary's College of California", aliases: ['Gaels', "Saint Mary's"] },
  { name: "Saint Peter's University", aliases: ['Peacocks', "Saint Peter's"] },
  { name: 'Sam Houston State University', aliases: ['Bearkats', 'Sam Houston'] },
  { name: 'Samford University', aliases: ['Bulldogs', 'Samford'] },
  { name: 'San Diego State University', aliases: ['Aztecs', 'San Diego State'] },
  { name: 'San Jose State University', aliases: ['San Jose State', 'Spartans'] },
  { name: 'Santa Clara University', aliases: ['Broncos', 'Santa Clara'] },
  { name: 'Seattle University', aliases: ['Redhawks', 'Seattle'] },
  { name: 'Seton Hall University', aliases: ['Pirates', 'Seton Hall'] },
  { name: 'Siena University', aliases: ['Saints', 'Siena'] },
  { name: 'South Carolina State University', aliases: ['Bulldogs', 'South Carolina State'] },
  { name: 'South Dakota State University', aliases: ['Jackrabbits', 'South Dakota State'] },
  { name: 'Southeast Missouri State University', aliases: ['Redhawks', 'SEMO'] },
  { name: 'Southeastern Louisiana University', aliases: ['Lions', 'Southeastern Louisiana'] },
  { name: 'Southern University', aliases: ['Jaguars', 'Southern', 'Southern University and A&M College'] },
  { name: 'Southern Illinois University Carbondale', aliases: ['Salukis', 'Southern Illinois'] },
  { name: 'Southern Illinois University Edwardsville', aliases: ['Cougars', 'SIUE'] },
  { name: 'Southern Methodist University', aliases: ['Mustangs', 'SMU'] },
  { name: 'Southern Utah University', aliases: ['Southern Utah', 'Thunderbirds'] },
  { name: 'University of Iowa', aliases: ['Hawkeyes', 'Iowa', 'State University of Iowa'] },
  { name: 'University at Albany', aliases: ['Albany', 'Great Danes', 'State University of New York at Albany'] },
  { name: 'Binghamton University', aliases: ['Bearcats', 'Binghamton', 'State University of New York at Binghamton'] },
  { name: 'University at Buffalo', aliases: ['Buffalo', 'Bulls', 'State University of New York at Buffalo'] },
  { name: 'Stony Brook University', aliases: ['Seawolves', 'State University of New York at Stony Brook', 'Stony Brook'] },
  { name: 'Stephen F. Austin State University', aliases: ['Lumberjacks', 'Stephen F. Austin'] },
  { name: 'Stetson University', aliases: ['Hatters', 'Stetson'] },
  { name: 'Stonehill College', aliases: ['Skyhawks', 'Stonehill'] },
  { name: 'Syracuse University', aliases: ['Orange', 'Syracuse'] },
  { name: 'Tarleton State University', aliases: ['Tarleton State', 'Texans'] },
  { name: 'Temple University', aliases: ['Owls', 'Temple'] },
  { name: 'Tennessee State University', aliases: ['Tennessee State', 'Tigers'] },
  { name: 'Tennessee Technological University', aliases: ['Golden Eagles', 'Tennessee Tech'] },
  { name: 'Texas A&M University', aliases: ['Aggies', 'Texas A&M'] },
  { name: 'Texas A&M University–Corpus Christi', aliases: ['Islanders', 'Texas A&M–Corpus Christi'] },
  { name: 'Texas Christian University', aliases: ['Horned Frogs', 'TCU'] },
  { name: 'Texas Southern University', aliases: ['Texas Southern', 'Tigers'] },
  { name: 'Texas State University', aliases: ['Bobcats', 'Texas State'] },
  { name: 'Texas Tech University', aliases: ['Red Raiders', 'Texas Tech'] },
  { name: 'The Citadel', aliases: ['Bulldogs'] },
  { name: 'William & Mary', aliases: ['The College of William and Mary in Virginia', 'Tribe'] },
  { name: 'George Washington University', aliases: ['George Washington', 'Revolutionaries', 'The George Washington University'] },
  { name: 'The Ohio State University', aliases: ['Buckeyes', 'OSU', 'Ohio State'] },
  { name: 'Ohio University', aliases: ['Bobcats', 'Ohio', 'The Ohio University'] },
  { name: 'The Pennsylvania State University', aliases: ['Nittany Lions', 'PSU', 'Penn State'] },
  { name: 'University of Akron', aliases: ['Akron', 'The University of Akron', 'Zips'] },
  { name: 'University of Alabama', aliases: ['Alabama', 'Crimson Tide', 'The University of Alabama'] },
  { name: 'University of Mississippi', aliases: ['Ole Miss', 'Rebels', 'The University of Mississippi'] },
  { name: 'University of New Mexico', aliases: ['Lobos', 'New Mexico', 'The University of New Mexico'] },
  { name: 'University of Tennessee at Chattanooga', aliases: ['Chattanooga', 'Mocs', 'The University of Tennessee at Chattanooga'] },
  { name: 'University of Tennessee at Martin', aliases: ['Skyhawks', 'The University of Tennessee at Martin', 'UT Martin'] },
  { name: 'University of Tennessee, Knoxville', aliases: ['Tennessee', 'The University of Tennessee, Knoxville', 'UT Knoxville', 'Volunteers'] },
  { name: 'University of Texas at Arlington', aliases: ['Mavericks', 'The University of Texas at Arlington', 'UT Arlington'] },
  { name: 'University of Texas at Austin', aliases: ['Longhorns', 'Texas', 'The University of Texas at Austin', 'UT Austin'] },
  { name: 'University of Texas at El Paso', aliases: ['Miners', 'The University of Texas at El Paso', 'UTEP'] },
  { name: 'University of Texas Rio Grande Valley', aliases: ['The University of Texas Rio Grande Valley', 'UTRGV', 'Vaqueros'] },
  { name: 'University of Texas at San Antonio', aliases: ['Roadrunners', 'The University of Texas at San Antonio', 'UTSA'] },
  { name: 'University of Tulsa', aliases: ['Golden Hurricane', 'The University of Tulsa', 'Tulsa'] },
  { name: 'University of Vermont', aliases: ['Catamounts', 'The University of Vermont and State Agricultural College', 'Vermont'] },
  { name: 'Towson University', aliases: ['Tigers', 'Towson'] },
  { name: 'Troy University', aliases: ['Trojans', 'Troy'] },
  { name: 'Tulane University of Louisiana', aliases: ['Green Wave', 'Tulane'] },
  { name: 'United States Air Force Academy', aliases: ['Air Force', 'Falcons'] },
  { name: 'United States Military Academy', aliases: ['Army', 'Army West Point', 'Black Knights'] },
  { name: 'United States Naval Academy', aliases: ['Midshipmen', 'Navy'] },
  { name: 'University of Alabama at Birmingham', aliases: ['Blazers', 'UAB'] },
  { name: 'University of Arizona', aliases: ['Arizona', 'Wildcats'] },
  { name: 'University of Arkansas', aliases: ['Arkansas', 'Razorbacks'] },
  { name: 'University of Arkansas at Little Rock', aliases: ['Little Rock', 'Trojans'] },
  { name: 'University of Arkansas at Pine Bluff', aliases: ['Arkansas–Pine Bluff', 'Golden Lions'] },
  { name: 'University of California, Berkeley', aliases: ['Berkeley', 'Cal', 'California', 'Golden Bears', 'UC Berkeley'] },
  { name: 'University of California, Davis', aliases: ['Aggies', 'UC Davis'] },
  { name: 'University of California, Irvine', aliases: ['Anteaters', 'UC Irvine'] },
  { name: 'University of California, Los Angeles', aliases: ['Bruins', 'UCLA'] },
  { name: 'University of California, Riverside', aliases: ['Highlanders', 'UC Riverside'] },
  { name: 'University of California, San Diego', aliases: ['Tritons', 'UC San Diego'] },
  { name: 'University of California, Santa Barbara', aliases: ['Gauchos', 'UC Santa Barbara'] },
  { name: 'University of Central Arkansas', aliases: ['Bears', 'Central Arkansas'] },
  { name: 'University of Central Florida', aliases: ['Knights', 'UCF'] },
  { name: 'University of Cincinnati', aliases: ['Bearcats', 'Cincinnati'] },
  { name: 'University of Colorado Boulder', aliases: ['Buffaloes', 'Colorado'] },
  { name: 'University of Connecticut', aliases: ['Huskies', 'UConn', 'UConn Huskies'] },
  { name: 'University of Dayton', aliases: ['Dayton', 'Flyers'] },
  { name: 'University of Delaware', aliases: ['Delaware', "Fightin' Blue Hens"] },
  { name: 'University of Denver', aliases: ['Denver', 'Pioneers'] },
  { name: 'University of Detroit Mercy', aliases: ['Detroit Mercy', 'Titans'] },
  { name: 'University of Evansville', aliases: ['Evansville', 'Purple Aces'] },
  { name: 'University of Florida', aliases: ['Florida', 'Gators'] },
  { name: 'University of Georgia', aliases: ['Bulldogs', 'Georgia'] },
  { name: 'University of Hawaiʻi at Mānoa', aliases: ['Hawaiʻi', 'Rainbow Warriors'] },
  { name: 'University of Houston', aliases: ['Cougars', 'Houston'] },
  { name: 'University of Idaho', aliases: ['Idaho', 'Vandals'] },
  { name: 'University of Illinois Chicago', aliases: ['Flames', 'UIC'] },
  { name: 'University of Illinois Urbana-Champaign', aliases: ['Fighting Illini', 'Illinois'] },
  { name: 'University of Kansas', aliases: ['Jayhawks', 'Kansas'] },
  { name: 'University of Kentucky', aliases: ['Kentucky', 'Wildcats'] },
  { name: 'University of Louisiana at Lafayette', aliases: ['Louisiana', "Ragin' Cajuns"] },
  { name: 'University of Louisiana at Monroe', aliases: ['ULM', 'Warhawks'] },
  { name: 'University of Louisville', aliases: ['Cardinals', 'Louisville'] },
  { name: 'University of Maine', aliases: ['Black Bears', 'Maine'] },
  { name: 'University of Maryland, Baltimore County', aliases: ['Retrievers', 'UMBC'] },
  { name: 'University of Maryland, College Park', aliases: ['Maryland', 'Terrapins'] },
  { name: 'University of Maryland Eastern Shore', aliases: ['Hawks', 'Maryland Eastern Shore'] },
  { name: 'University of Massachusetts Amherst', aliases: ['Minutemen', 'UMass', 'UMass Amherst'] },
  { name: 'University of Massachusetts Lowell', aliases: ['River Hawks', 'UMass Lowell'] },
  { name: 'University of Memphis', aliases: ['Memphis', 'Tigers'] },
  { name: 'University of Miami', aliases: ['Hurricanes', 'Miami (Florida)', 'Miami FL', 'U Miami'] },
  { name: 'University of Michigan', aliases: ['Michigan', 'Wolverines'] },
  { name: 'University of Minnesota', aliases: ['Golden Gophers', 'Minnesota'] },
  { name: 'University of Missouri', aliases: ['Missouri', 'Tigers', 'University of Missouri–Columbia'] },
  { name: 'University of Missouri–Kansas City', aliases: ['Kansas City', 'Roos'] },
  { name: 'University of Montana', aliases: ['Grizzlies', 'Montana'] },
  { name: 'University of Nebraska–Lincoln', aliases: ['Cornhuskers', 'Nebraska'] },
  { name: 'University of Nebraska Omaha', aliases: ['Mavericks', 'Omaha'] },
  { name: 'University of Nevada, Las Vegas', aliases: ['Rebels', 'UNLV'] },
  { name: 'University of Nevada, Reno', aliases: ['Nevada', 'Wolf Pack'] },
  { name: 'University of New Hampshire', aliases: ['New Hampshire', 'Wildcats'] },
  { name: 'University of New Orleans', aliases: ['New Orleans', 'Privateers'] },
  { name: 'University of North Alabama', aliases: ['Lions', 'North Alabama'] },
  { name: 'University of North Carolina at Asheville', aliases: ['Bulldogs', 'UNC Asheville'] },
  { name: 'University of North Carolina at Chapel Hill', aliases: ['Carolina', 'North Carolina', 'Tar Heels', 'UNC'] },
  { name: 'University of North Carolina at Charlotte', aliases: ['49ers', 'Charlotte'] },
  { name: 'University of North Carolina at Greensboro', aliases: ['Spartans', 'UNC Greensboro'] },
  { name: 'University of North Carolina at Wilmington', aliases: ['Seahawks', 'UNCW'] },
  { name: 'University of North Dakota', aliases: ['Fighting Hawks', 'North Dakota'] },
  { name: 'University of Northern Colorado', aliases: ['Bears', 'Northern Colorado'] },
  { name: 'University of Northern Iowa', aliases: ['Northern Iowa', 'Panthers'] },
  { name: 'University of North Florida', aliases: ['North Florida', 'Ospreys'] },
  { name: 'University of North Texas', aliases: ['Mean Green', 'North Texas'] },
  { name: 'University of Notre Dame du Lac', aliases: ['Fighting Irish', 'Notre Dame'] },
  { name: 'University of Oklahoma', aliases: ['Oklahoma', 'Sooners'] },
  { name: 'University of Oregon', aliases: ['Ducks', 'Oregon'] },
  { name: 'University of Pennsylvania', aliases: ['Penn', 'Quakers', 'UPenn'] },
  { name: 'University of Pittsburgh', aliases: ['Panthers', 'Pitt', 'Pittsburgh'] },
  { name: 'University of Portland', aliases: ['Pilots', 'Portland'] },
  { name: 'University of Rhode Island', aliases: ['Rams', 'Rhode Island'] },
  { name: 'University of Richmond', aliases: ['Richmond', 'Spiders'] },
  { name: 'University of Saint Thomas', aliases: ['Saint Thomas', 'Tommies'] },
  { name: 'University of San Diego', aliases: ['San Diego', 'Toreros'] },
  { name: 'University of San Francisco', aliases: ['Dons', 'San Francisco'] },
  { name: 'University of South Alabama', aliases: ['Jaguars', 'South Alabama'] },
  { name: 'University of South Carolina', aliases: ['Gamecocks', 'South Carolina', 'South Carolina Gamecocks'] },
  { name: 'University of South Carolina Upstate', aliases: ['Spartans', 'USC Upstate'] },
  { name: 'University of South Dakota', aliases: ['Coyotes', 'South Dakota'] },
  { name: 'University of Southern California', aliases: ['Trojans', 'USC', 'USC Trojans'] },
  { name: 'University of Southern Indiana', aliases: ['Screaming Eagles', 'Southern Indiana'] },
  { name: 'University of Southern Mississippi', aliases: ['Golden Eagles', 'Southern Miss'] },
  { name: 'University of South Florida', aliases: ['Bulls', 'South Florida'] },
  { name: 'University of the Incarnate Word', aliases: ['Cardinals', 'Incarnate Word'] },
  { name: 'University of the Pacific', aliases: ['Pacific', 'Tigers'] },
  { name: 'University of Toledo', aliases: ['Rockets', 'Toledo'] },
  { name: 'University of Utah', aliases: ['Utah', 'Utes'] },
  { name: 'University of Virginia', aliases: ['Cavaliers', 'Virginia'] },
  { name: 'University of Washington', aliases: ['Huskies', 'Washington'] },
  { name: 'University of Wisconsin–Green Bay', aliases: ['Green Bay', 'Phoenix'] },
  { name: 'University of Wisconsin–Madison', aliases: ['Badgers', 'Wisconsin'] },
  { name: 'University of Wisconsin–Milwaukee', aliases: ['Milwaukee', 'Panthers'] },
  { name: 'University of Wyoming', aliases: ['Cowboys', 'Wyoming'] },
  { name: 'Utah State University', aliases: ['Aggies', 'Utah State'] },
  { name: 'Utah Tech University', aliases: ['Trailblazers', 'Utah Tech'] },
  { name: 'Utah Valley University', aliases: ['Utah Valley', 'Wolverines'] },
  { name: 'Valparaiso University', aliases: ['Beacons', 'Valparaiso'] },
  { name: 'Vanderbilt University', aliases: ['Commodores', 'Vanderbilt'] },
  { name: 'Villanova University', aliases: ['Villanova', 'Wildcats'] },
  { name: 'Virginia Commonwealth University', aliases: ['Rams', 'VCU'] },
  { name: 'Virginia Military Institute', aliases: ['Keydets', 'VMI'] },
  { name: 'Virginia Polytechnic Institute and State University', aliases: ['Hokies', 'Virginia Tech'] },
  { name: 'Wagner College', aliases: ['Seahawks', 'Wagner'] },
  { name: 'Wake Forest University', aliases: ['Demon Deacons', 'Wake Forest'] },
  { name: 'Washington State University', aliases: ['Cougars', 'Washington State'] },
  { name: 'Weber State University', aliases: ['Weber State', 'Wildcats'] },
  { name: 'Western Carolina University', aliases: ['Catamounts', 'Western Carolina'] },
  { name: 'Western Illinois University', aliases: ['Leathernecks', 'Western Illinois'] },
  { name: 'Western Kentucky University', aliases: ['Hilltoppers', 'Western Kentucky'] },
  { name: 'Western Michigan University', aliases: ['Broncos', 'Western Michigan'] },
  { name: 'West Virginia University', aliases: ['Mountaineers', 'West Virginia'] },
  { name: 'Wichita State University', aliases: ['Shockers', 'Wichita State'] },
  { name: 'Rice University', aliases: ['Owls', 'Rice', 'William Marsh Rice University'] },
  { name: 'Winthrop University', aliases: ['Eagles', 'Winthrop'] },
  { name: 'Wofford College', aliases: ['Terriers', 'Wofford'] },
  { name: 'Wright State University', aliases: ['Raiders', 'Wright State'] },
  { name: 'Xavier University', aliases: ['Musketeers', 'Xavier'] },
  { name: 'Yale University', aliases: ['Bulldogs', 'Yale'] },
  { name: 'Youngstown State University', aliases: ['Penguins', 'Youngstown State'] },
  { name: 'Le Moyne College', aliases: ['Dolphins', 'Le Moyne'] },
  { name: 'Mercyhurst University', aliases: ['Lakers', 'Mercyhurst'] },
  { name: 'University of New Haven', aliases: ['Chargers', 'New Haven'] },
  { name: 'University of West Florida', aliases: ['Argonauts', 'West Florida'] },
  { name: 'University of West Georgia', aliases: ['West Georgia', 'Wolves'] },
];
